server:
  port: 8085

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/rahul-kibalabs/Hotel-Rating-System
          clone-on-start: true
  application:
    name: CONFIGSERVER





























logging:
  pattern:
    console: "${LOGPATTERN_CONSOLE:%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n}"